### ISSUE TITLE
[BUG] `filetype` not set on M1 Mac

### ISSUE THREAD

**Issue by dathinaios** [davidgranstrom/scnvim#182] opened 2022-04-23 10:39 UTC
**Describe the bug**
I just got a Mac Studio and trying to set everything up. `scnvim` stopped working though it was fine before the migration. I can see that the filetype is not set correctly and as a result `scnvim` files are set as scala filetype and `scd` as markdown (?!).

Worth noting that I had to do `:call scnvim#install()` manually as I got error `... Vim(call): E117: Unknown function: scnvim#install`.

I have added:

    au! BufWinEnter *.sc  setlocal filetype=supercollider
    au! BufWinEnter *.scd  setlocal filetype=supercollider
    au! BufWinEnter *.schelp  setlocal filetype=supercollider

to my `init.vim` and now the plugin seems to work as expected. As far as I can tell the only thing that is still broken after that is [tree-sitter-supercollider](https://github.com/madskjeldgaard/tree-sitter-supercollider). I will open an issue there but I thought maybe start with this bug as they may be related.

**System Info**

- Operating system
MacOS Monterey, `12.3.1`

- SuperCollider version
`3.12.2`

- `nvim --version`
```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.0/share/nvim"
```

- Package manager
`vim-plug`

**Comment by davidgranstrom** [comment] 2022-04-23 16:09
@dathinaios Thanks for your report. I'm on the same system as you and do not have this issue. Recently there was a [PR](https://github.com/davidgranstrom/scnvim/pull/180) merged that changed filetype detection, since nvim v0.7 should recognize `supercollider` filetype natively. Are you using the new filetype detection (`vim.g.do_filetype_lua = 1`) in your config?

Ping @ranjithshegde in case you have additional insight on this.

**Comment by ranjithshegde** [comment] 2022-04-23 16:24
The PR I submitted upstream (vim & nvim) automatically sets `scd` to supercollider, unless the very first  (and only first) line of the file starts with man-page preamble.
So, an empty `*.scd` file should say supercollider. 
@dathinaios, could you please verify without your `aucmd`, what filetype is displayed first on an empty `*.scd` file and then in a new instance on any `scd` with any contents?

**Comment by dathinaios** [comment] 2022-04-23 16:29
@davidgranstrom I have `let g:do_filetype_lua = 1` in my `init.vim` yes 🤔 
@ranjithshegde `scd` files (including a newly created one) are marked as `markdown` (?) and `sc` files as `scala`.

**Comment by ranjithshegde** [comment] 2022-04-23 16:32
if it can be reproduced with a minimal_init.lua (or minimal_init.vim) then its a bug upstream. 
@davidgranstrom does this repo have a minimal_init example?

**Comment by dathinaios** [comment] 2022-04-23 16:48
Good suggestion. I removed everything and (after the shock of seeing Vim without configuration) I tested and indeed the `filetype` is recognised correctly. I actually managed to narrow it down to my autocompletion configuration. I will paste that section of the config here in case something specific jumps out but apart from that I will need to troubleshoot further and come back to you.

```
    Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
    Plug 'nvim-treesitter/nvim-treesitter-refactor'
    Plug 'nvim-treesitter/playground'
    Plug 'haorenW1025/completion-nvim'
    Plug 'nvim-treesitter/completion-treesitter'
    Plug 'nvim-treesitter/nvim-treesitter-textobjects'
    Plug 'sheerun/vim-polyglot'

    Plug 'neovim/nvim-lspconfig'
    Plug 'williamboman/nvim-lsp-installer'

    Plug 'hrsh7th/cmp-nvim-lsp'
    Plug 'hrsh7th/cmp-buffer'
    Plug 'hrsh7th/cmp-path'
    Plug 'hrsh7th/cmp-cmdline'
    Plug 'hrsh7th/nvim-cmp'
    Plug 'ray-x/cmp-treesitter'
    Plug 'quangnguyen30192/cmp-nvim-tags'
		Plug	'hrsh7th/cmp-nvim-lua'

    " For vsnip users.
    Plug 'hrsh7th/cmp-vsnip'

    " Snippets {{{
    Plug 'rafamadriz/friendly-snippets'
    Plug 'hrsh7th/vim-vsnip'
    Plug 'L3MON4D3/LuaSnip'
    Plug 'saadparwaiz1/cmp_luasnip'
    let g:scnvim_snippet_format = "luasnip"

    " Jump forward or backward in vsnip
    imap <expr> <Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)'      : '<Tab>'
    smap <expr> <Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)'      : '<Tab>'
    imap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'
    smap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'

    " and here for luasnip
    imap <silent><expr> <Tab> luasnip#expand_or_jumpable() ? '<Plug>luasnip-expand-or-jump' : '<Tab>'
    " -1 for jumping backwards.
    inoremap <silent> <S-Tab> <cmd>lua require'luasnip'.jump(-1)<Cr>

    snoremap <silent> <Tab> <cmd>lua require('luasnip').jump(1)<Cr>
    snoremap <silent> <S-Tab> <cmd>lua require('luasnip').jump(-1)<Cr>

```

**Comment by ranjithshegde** [comment] 2022-04-23 16:59
I have not used polyglot in ages so I dont remember how it asserts filetypes and syntaxes. Could it be the culprit?
As a side note, are you using any filetypes that dont have a tree-sitter parser? if not, then polyglot + tree-sitter is heavy. You might consider moving away from it

**Comment by dathinaios** [comment] 2022-04-23 17:13
That was it! Not only it fixed the issue with the `filetype` but [tree-sitter-supercollider](https://github.com/madskjeldgaard/tree-sitter-supercollider) is now working as well! I don't even know why I had polyglot there. I assume it was a copy paste as I was trying to fix auto complete during the past month.

Grateful for the help! I don't know if you want to keep this open but from my side feel free to close.

**Closed** 2022-05-18 11:14 UTC
Labels: bug
