### ISSUE TITLE
[BUG] Neovim does not exit cleanly when SCNvim Is running

### ISSUE THREAD

**Issue by john-d-murphy** [davidgranstrom/scnvim#105] opened 2020-07-11 12:45 UTC
**Describe the bug**
NeoVim does not exit cleanly when SCNVim is running 

**Expected behavior**
Vim is expected to exit, shutdown and close down all udp connections

**Steps to reproduce**
On a Linux Machine - start vim from the terminal -> run scnvim -> attempt to close -> vim processs will close, but remain hung at the terminal until Control+C is pressed.

**Additional context**
It looks like the shutdown logic works properly if SCNvimClose is called prior to shutdown, so it doesn't seem to be a problem with the shutdown lua code block itself. The AutoCmd appears to not be called, verified by putting a false 'Assert' in the shutdown code. 

I confirmed that this wasn't an issue with my specific vim setup by removing all other plugins but SCNvim and then restarting - I see this behavior even with only the single plugin installed. 

**Information**
- `nvim --version`:v0.4.3
- Operating system: 5.7.4-gentoo-x86_64
- Running scnvim in a Terminal/GUI: Terminal

**Comment by davidgranstrom** [comment] 2020-07-12 14:19
@john-d-murphy Thanks for the report. I cannot reproduce what you describe with nvim v0.4.3 on macOS, but I'll see if I can reproduce it on my linux machine. A long shot, but does anything change if you change the `autocmd` to trigger on `VimLeave` instead of `VimLeavePre`? It's defined on line 10 in `autoload/sclang.vim`.

**Comment by john-d-murphy** [comment] 2020-07-12 21:32
I've tried it with both and neither seems to work. I'd be willing to take this as a bug with my setup, since using neovim and gentoo is probably not the most standard of configurations.

**Comment by davidgranstrom** [comment] 2020-07-13 19:05
Ok, I see. Running the command below, do you see "exiting" being printed in your terminal? If not, this indicates indeed that this is probably a bug with nvim. 

```shell
nvim --clean --cmd 'au VimLeavePre * echo "exiting" | sleep' +qa
```

Do you have the possibility to upgrade from v0.4.3 to a nightly build (just to see if it is fixed upstream)?

**Comment by john-d-murphy** [comment] 2020-07-13 23:35
I do see that in my terminal when I go to leave vim. Per your request, I updated to the development head of neovim, and sure enough the issue is resolved. I think you can file this away as an upstream bug and not one with the plugin itself.

**Comment by davidgranstrom** [comment] 2020-07-14 08:18
Okay! I'm glad that it's already fixed upstream, I'll close this issue for now.

**Closed by davidgranstrom** 2020-07-14 08:18 UTC
Labels: bug, solution
