### ISSUE TITLE
Help system intermittently broken on Linux

### ISSUE THREAD

**Issue by kflak** [davidgranstrom/scnvim#48] opened 2019-11-21 07:23 UTC
The last few days the pandoc-help has been crashing for no reason I can figure out, delivering me this kind of stuff:
```
ERROR: Primitive '_NetAddr_SendRaw' failed.
caught exception 'send_to: Invalid argument' in primitive in method NetAddr:sendRaw
RECEIVER:
Instance of NetAddr {    (0x55ef5b5cee08, gc=60, fmt=00, flg=00, set=02)
  instance variables [4]
    addr : Integer 2130706433
    port : Integer 0
    hostname : "127.0.0.1"
    socket : nil
}
CALL STACK:
	MethodError:reportError
		arg this = <instance of PrimitiveFailedError>
	Nil:handleError
		arg this = nil
		arg error = <instance of PrimitiveFailedError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of PrimitiveFailedError>
	Object:throw
		arg this = <instance of PrimitiveFailedError>
	Object:primitiveFailed
		arg this = <instance of NetAddr>
	Meta_SCNvim:sendJSON
		arg this = <instance of Meta_SCNvim>
		arg object = "{"action":{"help":{"uri":"/h..."
		arg vimPort = 0
	Meta_SCNvim:openHelpFor
		arg this = <instance of Meta_SCNvim>
		arg text = "SynthDef"
		arg vimPort = 0
		arg pattern = ""
		arg pandocPath = "/usr/bin/pandoc"
		var msg = "{"action":{"help":{"uri":"/h..."
		var uri = <instance of URI>
		var path = "/home/kf/.local/share/SuperC..."
		var outputPath = "/home/kf/.local/share/SuperC..."
	Process:interpretCmdLine
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Primitive '_NetAddr_SendRaw' failed.
caught exception 'send_to: Invalid argument' in primitive in method NetAddr:sendRaw
RECEIVER: a NetAddr(127.0.0.1, 0)
```
Last time it happened,  the system seemed to reset itself (maybe the port was freed up? I don't really know...) and I was able to use the help in scnvim as before. 
System: Arch Linux 5.2.21-rt13-1-rt.
Neovim version: 0.4.3
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include

Output of `:checkhealth`:
```
health#scnvim#check
========================================================================
## scnvim
  - OK: has("timers") - success
  - INFO: sclang executable: /usr/bin/sclang
  - INFO: pandoc executable: /usr/bin/pandoc
  - INFO: has("python3") - success

health#defx#check
========================================================================
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='5602'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: wl-copy

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.8 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.8.0
  - INFO: pynvim version: 0.4.0
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
  - INFO: Host: /home/kf/.gem/ruby/2.6.0/bin/neovim-ruby-host
  - OK: Latest "neovim" gem is installed: 0.8.1

## Node.js provider (optional)
  - INFO: Node.js: v13.1.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
```
I tried reinstalling scnvim, but that didn't help either...

**Comment by davidgranstrom** [comment] 2019-11-21 12:31
@kflak Thanks for the report! That is indeed strange, looks like the port couldn't be opened based on the log you sent (`... port : Integer 0 ...`). 

Does it work if you manually set the port to something else, like `let g:scnvim_udp_port = 8300` in your init.vim?

I recently changed how the remote plugin (python) is invoked, it now happens after `:SCNvimStart` and before it was invoked for `*.sc,*.scd` file patterns. You could try and revert the scnvim plugin to commit `fda2bb0` before this change was introduced and see if that helps.

**Comment by kflak** [comment] 2019-11-21 16:58
Hi there,
Unfortunately none of the above seem to do the trick. I don't know if it helps, but the troubles started after I started doing some work in sc-ide... Could this have hogged my ports?

**Comment by davidgranstrom** [comment] 2019-11-22 14:30
@kflak Okay, thanks for the info. The scnvim help system was designed to be decoupled from the default help system, and the remote plugin should also try to find an open port in case the default one is unavailable.

Could you try and start scnvim and then see what `:echo g:scnvim_python_port` returns?

**Comment by kflak** [comment] 2019-11-22 14:58
Hey there, I'm getting a `v: null`

**Comment by davidgranstrom** [comment] 2019-11-22 15:05
Ok, I need to take a closer look and investigate why that is. Have you also tried `:UpdateRemotePlugins`?

**Comment by kflak** [comment] 2019-11-22 17:36
Yup, I have it running automatically like this:
`Plug 'davidgranstrom/scnvim', { 'do': ':UpdateRemotePlugins' }`. Additionally I tried doing it manually. No joy...

**Comment by kflak** [comment] 2019-11-22 19:29
OK, I think I found the doggy: downgrading to the previous version of pynvim solves the issue.

**Comment by bagong** [comment] 2019-11-23 01:47
On MacOS it also breaks with pynwin 0.4.0

**Comment by davidgranstrom** [comment] 2019-11-23 09:14
Sorry, I thought I was on the latest pynvim too but had forgot to upgrade. I will push a fix for this in a moment that hopefully will resolve this.

**Comment by kflak** [comment] 2019-11-23 19:01
Works, thanks!

**Closed** 2019-11-23 19:02 UTC
