### ISSUE TITLE
[BUG] Error when launching :SCNvimStart

### ISSUE THREAD

**Issue by tomschelsen** [davidgranstrom/scnvim#73] opened 2020-05-09 09:30 UTC
Trying to set up SCNvim following the README. First, the symbolic link command line given for Linux is ln [...] /Extensions/scide_scvim but as the MacOS one links to [...]/Extensions/scide_scvim/scnvim and the comment says "in the 'scide_scvim' directory named 'scnvim' ", I linked to [...]/Extensions/scide_scvim/scnvim instead. In my setup plugs get installed in ~/.config/nvim/autoload/plugged/, so the final command was :  ln -s /home/tom/.config/nvim/autoload/plugged/scnvim/sc /home/tom/.local/share/SuperCollider/Extensions/scide_scvim/scnvim
 
Opening a .scd file and launching :SCNvimStart results in the following error in the post-window : 
```

ERROR: Message 'dir' not understood.
RECEIVER:
class Document (0x556dec905140) {
  instance variables [19]
    name : Symbol 'Document'
    nextclass : instance of Meta_DocumentFile (0x556defd7e580, size=19, set=5)
    superclass : Symbol 'Object'
    subclasses : nil
    methods : instance of Array (0x556df0724540, size=5, set=3)
    instVarNames : instance of SymbolArray (0x556dec905380, size=2, set=2)
    classVarNames : nil
    iprototype : instance of Array (0x556dec905440, size=2, set=2)
    cprototype : nil
    constNames : nil
    constValues : nil
    instanceFormat : Integer 0
    instanceFlags : Integer 0
    classIndex : Integer 1270
    classFlags : Integer 0
    maxSubclassIndex : Integer 1270
    filenameSymbol : Symbol '/home/tom/.local/share/SuperCollider/Extensions/scide_scvim/scnvim/Classes/Document.sc'
    charPos : Integer 33
    classVarIndex : Integer 614
}
ARGS:
CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand
		arg this = <instance of Meta_Document>
		arg selector = 'dir'
		arg args = [*0]
	Meta_Instr:initClass
		arg this = <instance of Meta_Instr>
	Meta_Class:initClassTree
		arg this = <instance of Meta_Class>
		arg aClass = <instance of Meta_Instr>
		var implementsInitClass = nil
	ArrayedCollection:do
		arg this = [*939]
		arg function = <instance of Function>
		var i = 234
	Meta_Class:initClassTree
		arg this = <instance of Meta_Class>
		arg aClass = <instance of Meta_Object>
		var implementsInitClass = nil
	Process:startup
		arg this = <instance of Main>
		var time = 1.910168958
	Main:startup
		arg this = <instance of Main>
		var didWarnOverwrite = false
^^ The preceding error dump is for ERROR: Message 'dir' not understood.
RECEIVER: Document
```

Any idea what might cause this ? Thanks.

**Information**
- `nvim --version`: 0.4.3, using Vim-plug
- Operating system: Arch linux
- Running scnvim in a Terminal/GUI: terminal is Tilix, Supercollider 3.11.0

**Comment by davidgranstrom** [comment] 2020-05-09 10:45
@tomschelsen Thanks for the report! Your setup (with symlinks) looks correct, the problem is because of the lack of `Document` support in scnvim at the moment. The specific error that you posted is related to the `Instr` quark, and triggered because scnvim Document has not implemented the `dir` classvar yet. I will log this as an issue and try to resolve it as quickly as possible.

**Comment by davidgranstrom** [comment] 2020-05-09 11:14
@tomschelsen I just merged a fix, hope it works as expected now!

**Comment by tomschelsen** [comment] 2020-05-09 13:10
Wow that was fast, it does work now, thanks a lot !

**Closed** 2020-05-09 13:13 UTC
Labels: bug
